name: Run test & large tests daily
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  job_build_and_test:
    runs-on: ubuntu-18.04
    container:
      image: docker://docker:stable-git
      options: --name=runner
    strategy:
      matrix:
        android_api: [29,30]
        android_ndk: ["--android-ndk"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Build and large tests
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: ./ci_cd.sh --build --test --large-test --android-api ${{ matrix.android_api }} ${{ matrix.android_ndk }} --gcloud
